### PR TITLE
Documentation of Biglow Canyon case

### PR DESCRIPTION
**Pull request by rthedin**
Adding documentation and description of the complex terrain case over the Biglow Canyon wind farm. The setup of this case has already been pushed to the appropriate repository.

@phawbeck please take a look at the syntax. I wrote this blindly without sphinx, so there might be one or two syntax problems.

### CODE REVIEW

**Comment by hawbecker** [comment]
This is kind of tricky to do from my end, so it'll probably be easier for you to add it to the commit. Can you update cases.rst to include the wfip2_biglow.rst file in the toctree:
```
.. toctree::
  :glob:
  :maxdepth: 1
  
  cases/swift.rst
  cases/fino.rst
  cases/wfip2.rst
  cases/wfip2_biglow.rst
  cases/nyserda.rst
```
After that, it all looked good on my end!

**Comment by hawbecker** [comment]
One more thing - it looks like the link to the SOWFA repository doesn't go where you want it to. It's taking me to the NREL github and there are not any notebooks.

**Comment by rthedin** [comment]
Thanks Pat. I added the case to the table of contents and updated some SOWFA links. We don't have a a2e-dedicated flavor of SOWFA, so I linked to the general repository.

I'm aware about that link not having a notebook just yet, but I appreciate you catching that! I will push it soon. I figured that link can already be in place. A handful of SOWFA scripts/tools need to go there.

**Comment by hawbecker** [comment]
Ok - got it! Will there be a SOWFA-setup and assessment directory for this on the MMC repo? Is it possible to host the information you're thinking of including on the MMC repo instead / as well?

**Comment by hawbecker** [comment]
It also looks like there is a place for this on the MMC repo: https://github.com/a2e-mmc/SOWFA-models

**Comment by rthedin** [comment]
By the way, [SOWFA-models](https://github.com/a2e-mmc/SOWFA-models) is old, not maintained, and has a misleading name. Those are essentially tutorial files that we keep [within](https://github.com/NREL/SOWFA-6/tree/dev/exampleCases) the SOWFA repository. I'm usually the person keeping those tutorial files updated.

That is to say.. I'm not sure where the SOWFA-models repository fits and what we should do with it.

**Comment by hawbecker** [comment]
Ok - we can always repurpose SOWFA-models if it's unused. Maybe @mchurchf and/or @ewquon have an idea about what to do with it. It might be a good thing (or even a requirement) to have all of this under the MMC umbrella.

**Comment by rthedin** [comment]
> Ok - got it! Will there be a SOWFA-setup and assessment directory for this on the MMC repo? Is it possible to host the information you're thinking of including on the MMC repo instead / as well?

We have a SOWFA-setups for the actual cases that we run. That's the repo that I asked permissions a few days ago and pushed our cases to. I was not planning on having a SOWFA-specific `assessment` directory. My idea was to put assessments of SOWFA cases inside a2e/assessments/studies. I haven't gone that far yet, but that was my plan. Happy to hear your thoughts on the organization. 

Finally, I really think SOWFA-models don't make sense since we don't have a "WRF-models".

**Comment by hawbecker** [comment]
Yeah, I was thinking an assessment directory for the case, now SOWFA, itself. And we do host MMC-WRF on the repo: https://github.com/a2e-mmc/WRF
We can always rename "SOWFA-models" to "SOWFA" for consistency.

Let's take this offline since it isn't necessary for this PR right now. We can modify later.

**Pull request merged**
